import { LegalLayout } from '../_components/LegalLayout';

export const metadata = {
  title: 'Privacy Policy — OpenBook',
  description: 'Privacy Policy for OpenBook by OpenHouse AI Limited.',
};

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" effective="27 April 2026" version="1.0">
      <p>This Privacy Policy explains what personal data OpenBook collects, why we collect it, how long we keep it, and what rights you have over it. We&apos;ve written it to be readable, not just compliant.</p>

      <p>OpenBook is operated by <strong>OpenHouse AI Limited</strong> (&ldquo;we&rdquo;, &ldquo;us&rdquo;), an Irish company. We are the data controller for the personal data described in this policy.</p>

      <ul>
        <li><strong>Registered office:</strong> Ballinvarosig, Carrigaline, Co. Cork, Ireland</li>
        <li><strong>Data contact:</strong> <a href="mailto:sam@evolvai.ie">sam@evolvai.ie</a></li>
      </ul>

      <h2>1. Who this policy covers</h2>

      <p>This policy covers two groups:</p>

      <ul>
        <li><strong>Businesses</strong> — owners and staff who sign in to OpenBook to manage bookings.</li>
        <li><strong>Consumers</strong> — people who use OpenBook (signed in, or as guests) to book services.</li>
      </ul>

      <p>We treat both groups&apos; data with the same level of care, but we collect different things from each.</p>

      <h2>2. What we collect, and why</h2>

      <h3>From businesses (account holders)</h3>

      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Why we have it</th>
            <th>Source</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Name and email</td>
            <td>To create the account and contact you</td>
            <td>You provide it (or via Google/Apple sign-in)</td>
          </tr>
          <tr>
            <td>Business name, address, phone, website</td>
            <td>To list your business publicly</td>
            <td>You provide it during onboarding</td>
          </tr>
          <tr>
            <td>Logo, photos, descriptions</td>
            <td>To display your booking page</td>
            <td>You upload them</td>
          </tr>
          <tr>
            <td>Business hours, services, pricing</td>
            <td>To run the booking engine</td>
            <td>You configure them</td>
          </tr>
          <tr>
            <td>Stripe Connect account details</td>
            <td>To pay you out for bookings</td>
            <td>You authorise Stripe; we receive a Stripe ID, not bank details</td>
          </tr>
          <tr>
            <td>Booking and customer data for your business</td>
            <td>To run your business on the platform</td>
            <td>Generated as your customers book</td>
          </tr>
          <tr>
            <td>WhatsApp number and conversation history (if Pro tier)</td>
            <td>To run the WhatsApp bot for you</td>
            <td>Generated when customers message you</td>
          </tr>
          <tr>
            <td>Subscription and billing data</td>
            <td>To manage your subscription</td>
            <td>Generated as you subscribe</td>
          </tr>
        </tbody>
      </table>

      <h3>From consumers</h3>

      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Why we have it</th>
            <th>Source</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Name, phone, email</td>
            <td>To confirm and remind about bookings</td>
            <td>You provide it at checkout</td>
          </tr>
          <tr>
            <td>Booking history</td>
            <td>To show you upcoming and past bookings</td>
            <td>Generated by your bookings</td>
          </tr>
          <tr>
            <td>Saved businesses (favourites)</td>
            <td>To populate your home screen</td>
            <td>You favourite a business</td>
          </tr>
          <tr>
            <td>Payment card details</td>
            <td>To process the booking</td>
            <td><strong>Sent directly to Stripe — we never see or store these</strong></td>
          </tr>
          <tr>
            <td>Account credentials (if signed in)</td>
            <td>To recognise you across visits</td>
            <td>You provide via Google, Apple or magic link</td>
          </tr>
        </tbody>
      </table>

      <h3>Automatically collected (both groups)</h3>

      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Why we have it</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>IP address, browser type, device</td>
            <td>Security, fraud prevention, debugging</td>
          </tr>
          <tr>
            <td>Page views (anonymous, no cookies)</td>
            <td>To understand what&apos;s working — see Cookies section</td>
          </tr>
          <tr>
            <td>Crash and error logs</td>
            <td>To fix bugs</td>
          </tr>
        </tbody>
      </table>

      <h2>3. Our lawful basis (GDPR Article 6)</h2>

      <p>We process personal data on these bases:</p>

      <ul>
        <li><strong>Contract</strong> — most processing happens because you (consumer or business) have asked us to provide a service. Booking processing, account management, payment processing, sending booking confirmations.</li>
        <li><strong>Legitimate interest</strong> — running the platform, fraud prevention, security, anonymous analytics. We&apos;ve assessed that our interest doesn&apos;t override your rights.</li>
        <li><strong>Consent</strong> — for any future marketing emails, optional cookies, or Instagram content pulling. We&apos;ll always ask first and you can withdraw at any time.</li>
        <li><strong>Legal obligation</strong> — keeping financial records (Stripe transaction records) for tax purposes.</li>
      </ul>

      <h2>4. Where your data lives</h2>

      <p>Your data is stored in the <strong>European Union</strong>. Specifically:</p>

      <ul>
        <li><strong>Database (Supabase)</strong> — Dublin, Ireland (AWS eu-west-1).</li>
        <li><strong>Hosting (Vercel)</strong> — primarily served from Dublin (dub1) edge.</li>
        <li><strong>Files (Supabase Storage)</strong> — Dublin, Ireland.</li>
      </ul>

      <h2>5. Who we share data with (sub-processors)</h2>

      <p>We use third parties to deliver parts of the service. Each one only gets the data they need to do their job, and each is contractually required to handle it according to GDPR.</p>

      <table>
        <thead>
          <tr>
            <th>Sub-processor</th>
            <th>What they do</th>
            <th>Data they see</th>
            <th>Where</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Supabase</td>
            <td>Database, auth, storage</td>
            <td>All operational data</td>
            <td>EU (Ireland)</td>
          </tr>
          <tr>
            <td>Vercel</td>
            <td>App hosting and edge functions</td>
            <td>All data passing through requests</td>
            <td>EU + global edge</td>
          </tr>
          <tr>
            <td>Stripe</td>
            <td>Payment processing, payouts</td>
            <td>Card details, transaction data, business KYC</td>
            <td>Global; EU contracts</td>
          </tr>
          <tr>
            <td>Resend</td>
            <td>Transactional email</td>
            <td>Recipient email, message content</td>
            <td>US (under SCCs)</td>
          </tr>
          <tr>
            <td>OpenAI</td>
            <td>AI insights, AI assistant features (Pro tier)</td>
            <td>Aggregated booking data; never raw customer data</td>
            <td>US (under SCCs); no model training on your data</td>
          </tr>
          <tr>
            <td>Meta (WhatsApp Cloud API)</td>
            <td>WhatsApp bot (Pro tier, opt-in)</td>
            <td>WhatsApp messages, phone numbers</td>
            <td>US (under SCCs)</td>
          </tr>
        </tbody>
      </table>

      <p>We do <strong>not</strong> sell, rent, or share your data with advertisers, data brokers, or anyone else not listed above.</p>

      <p>For US-based sub-processors (Stripe, Resend, OpenAI, Meta), data transfers are protected by Standard Contractual Clauses (SCCs) approved by the European Commission. This is the legal mechanism under GDPR for sending personal data outside the EEA.</p>

      <h2>6. AI and your data</h2>

      <p>This deserves its own section because people ask.</p>

      <ul>
        <li><strong>OpenAI</strong> is used for AI insights (analysing your business&apos;s anonymised aggregated data to surface &ldquo;you have 3 empty slots Friday — try a flash sale&rdquo;) and the AI assistant. We send OpenAI <strong>summaries and aggregates</strong>, not raw customer records.</li>
        <li><strong>OpenAI does not train on data sent through their API</strong>, per their published API data policy. We do not opt into any &ldquo;improve our models&rdquo; setting.</li>
        <li><strong>We never use your data, your customers&apos; data, or anyone&apos;s bookings to train our own AI models.</strong> We don&apos;t have AI models — we use third-party APIs.</li>
        <li>The MCP server (Pro tier, <a href="http://mcp.openbook.ie">mcp.openbook.ie</a>) shares <strong>business-level data</strong> (your name, services, prices, live availability, location) with AI assistants like ChatGPT, Claude, and Gemini. It never shares customer data or bookings.</li>
      </ul>

      <h2>7. How long we keep your data</h2>

      <table>
        <thead>
          <tr>
            <th>Data</th>
            <th>Retention</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Active account data</td>
            <td>For as long as your account is active</td>
          </tr>
          <tr>
            <td>Booking records</td>
            <td>7 years (Irish tax/accounting requirement)</td>
          </tr>
          <tr>
            <td>Customer-facing booking page after account closure</td>
            <td>30 days, then archived for 12 months, then deleted</td>
          </tr>
          <tr>
            <td>Backups</td>
            <td>30 days rolling</td>
          </tr>
          <tr>
            <td>Payment transaction records (Stripe)</td>
            <td>Per Stripe&apos;s policy, typically 7+ years</td>
          </tr>
          <tr>
            <td>WhatsApp conversation history</td>
            <td>24 months from last activity</td>
          </tr>
          <tr>
            <td>Anonymous analytics</td>
            <td>Indefinite (no personal data)</td>
          </tr>
        </tbody>
      </table>

      <p>When you ask us to delete your data, we delete it from our active systems within 30 days, and from backups within a further 30 days. We may retain records we&apos;re legally required to keep (tax records, fraud investigations).</p>

      <h2>8. Your rights</h2>

      <p>Under GDPR you have the right to:</p>

      <ul>
        <li><strong>Access</strong> — ask for a copy of the personal data we hold about you.</li>
        <li><strong>Rectify</strong> — correct anything that&apos;s wrong.</li>
        <li><strong>Erase</strong> — ask us to delete your data (&ldquo;right to be forgotten&rdquo;), subject to legal retention rules above.</li>
        <li><strong>Restrict processing</strong> — ask us to stop processing while a query is being resolved.</li>
        <li><strong>Portability</strong> — get your data in a structured machine-readable format. (You can do this directly from the dashboard at any time — full CSV export.)</li>
        <li><strong>Object</strong> — object to processing based on legitimate interest.</li>
        <li><strong>Withdraw consent</strong> — for anything we do based on consent (marketing, etc.).</li>
        <li><strong>Lodge a complaint</strong> — with the Irish Data Protection Commission (<a href="http://dataprotection.ie">dataprotection.ie</a>) if you think we&apos;ve handled your data wrongly.</li>
      </ul>

      <p>To exercise any of these, email <a href="mailto:sam@evolvai.ie">sam@evolvai.ie</a>. We&apos;ll respond within 30 days.</p>

      <h2>9. Security</h2>

      <p>We protect data with:</p>

      <ul>
        <li>HTTPS everywhere (TLS 1.3)</li>
        <li>Row-level security on every database table</li>
        <li>Authentication via Google, Apple, or signed magic-link emails (no passwords for us to leak)</li>
        <li>Card data never touches our servers (handled directly by Stripe)</li>
        <li>Restricted access to production data — only Sam Donworth currently has it</li>
        <li>Encrypted at rest (Supabase default)</li>
      </ul>

      <p>If we ever discover a personal data breach, we&apos;ll notify the Irish DPC within 72 hours and tell affected users without undue delay, as required by GDPR.</p>

      <h2>10. Children</h2>

      <p>OpenBook is not intended for users under 16. We don&apos;t knowingly collect data from anyone under 16. If you believe we&apos;ve inadvertently collected such data, email <a href="mailto:sam@evolvai.ie">sam@evolvai.ie</a> and we&apos;ll delete it.</p>

      <h2>11. International users</h2>

      <p>OpenBook is targeted at the Irish market. If you&apos;re using it from outside Ireland (e.g. a tourist booking an Irish service), the same protections apply — your data is still hosted in the EU.</p>

      <h2>12. Changes to this policy</h2>

      <p>If we change this policy in a material way, we&apos;ll email you and show the changes at openbook.ie/privacy with a new effective date. Minor wording fixes won&apos;t trigger a notification.</p>

      <h2>13. Contact</h2>

      <p><strong>Data queries:</strong> <a href="mailto:sam@evolvai.ie">sam@evolvai.ie</a><br />
      <strong>Post:</strong> OpenHouse AI Limited, Ballinvarosig, Carrigaline, Co. Cork, Ireland</p>

      <p><strong>Supervisory authority (Ireland):</strong><br />
      Data Protection Commission<br />
      21 Fitzwilliam Square South, Dublin 2, D02 RD28<br />
      <a href="http://dataprotection.ie">dataprotection.ie</a></p>

      <hr />

      <div className="legal-footer-note">
        <p><em>OpenHouse AI Limited, trading as OpenBook. Registered in Ireland.</em></p>
        <p><em>This document is version 1.0, effective 27 April 2026.</em></p>
      </div>
    </LegalLayout>
  );
}
